{{- if and .Values.migration .Values.migration.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "default.fullname" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  {{- if .Values.migration.backoffLimit }}
  backoffLimit: {{ .Values.migration.backoffLimit }}
  {{- end }}
  {{- if .Values.migration.activeDeadlineSeconds }}
  activeDeadlineSeconds: {{ .Values.migration.activeDeadlineSeconds }}
  {{- end }}
  {{- if .Values.migration.ttlSecondsAfterFinished }}
  ttlSecondsAfterFinished: {{ .Values.migration.ttlSecondsAfterFinished }}
  {{- end }}
  template:
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.migration.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- include "default.common-spec_container" . | nindent 10 }}
          {{- if .Values.migration.resources }}
          resources:
            {{- toYaml .Values.migration.resources | nindent 12 }}
          {{- end }}
          {{- with .Values.migration.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.migration.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.migration.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- with .Values.migration.sidecars }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.migration.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: "Never"
{{- end }}
